---
language: bash

# Tell Travis to start Docker when it brings up an environment.
services:
  - docker

env:
  # Provide a list of OSes we want to use for testing.
  - DISTRIBUTION: debian8
  - DISTRIBUTION: debian9
  - DISTRIBUTION: centos7

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export CLEANUP=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/Turgon37/5b6e6553ef92dc65d1c7df3e1a1e290e/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Prepare network
   - function test_begin_user() { ip addr }
   - export -f function test_begin_user
#  - export iface=$(ip link | grep '^[0-9].*state UP' | awk '{ print $2 }' |tr -d ':' | head -n 1)
#  - ip addr add 192.168.1.254/24 dev $iface

  # Run tests.
  - ${PWD}/tests/test.sh
  - docker exec --tty --env TERM=xterm ${container_id} journalctl -xn
  - docker exec --tty --env TERM=xterm ${container_id} ip addr
  - export container_id=$(cat /tmp/container_id)

  #
  ## Specific roles tests
  #
  # Ensure dhcpd is installed.
  - docker exec --tty --env TERM=xterm ${container_id} which dhcpd
  - docker exec --tty --env TERM=xterm ${container_id} dhcpd --version
