---

- name: Install default configuration file
  template:
    src:   default-dhcpd.j2
    dest:  '/etc/default/isc-dhcp-server'
    owner: root
    group: root
    mode:  0644
  when: ansible_distribution == 'Debian'
  notify: [ 'restart-dhcpd' ]

- name: Include the dhcpd mode's tasks
  include_tasks: 'configure-mode-{{ dhcpd__mode }}.yml'
