---

- name: Assert required LDAP variables
  assert:
    that:
      - dhcpd__ldap_server is defined
      - dhcpd__ldap_basedn is defined
      - dhcpd__ldap_method in ['static', 'dynamic']
      - dhcpd__ldap_ssl is not defined or dhcpd__ldap_ssl in ['start_tls', 'ldaps']

- name: Configure DHCP server
  template:
    src:   'dhcpd.conf.ldap.j2'
    dest:  '{{ dhcpd__config_file }}'
    owner: root
    group: root
    mode:  0644
    validate: '{{ dhcpd__executable }} -t -cf %s'
  notify: [ 'restart-dhcpd' ]
