---

- name: Ensure configuration directory exists
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '{{ dhcpd__configuration_directory }}'

- name: Install service environment file
  template:
    src: dhcpd.environment.j2
    dest: '{{ dhcpd__service_environment }}'
    owner: root
    group: root
    mode:  0644
  when: dhcpd__service_environment is defined
  notify: [ 'restart-dhcpd' ]

- name: Include the dhcpd mode's tasks
  include_tasks: 'configure-mode-{{ dhcpd__mode }}.yml'
