---

- name: Ensure configuration directory exists
  file:
    path: '{{ item }}'
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - '{{ dhcpd__configuration_directory }}'
