---
# TODO
- name: Assert required FILES variables
  assert:
    that:
      - True

- name: Configure DHCP server
  template:
    src:   'dhcpd.conf.files.j2'
    dest:  '{{ dhcpd__config_file }}'
    owner: root
    group: root
    mode:  0644
    validate: '{{ dhcpd__executable }} -t -cf %s'
  notify: [ 'restart-dhcpd' ]
