---

- name: Assert global required variables
  assert:
    that:
      - dhcpd__service_environment is defined

- name: Assert required variables per instances
  assert:
    that:
      - dhcpd__instance.mode is defined
  vars:
    dhcpd__instance: "{{ dhcpd__instance_defaults|combine(outer_item.value)|combine({'name': outer_item.key}) }}"
  with_dict: '{{ dhcpd__instances }}'
  loop_control:
    loop_var: outer_item
