---

- name: Install dhcpd packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ dhcpd__packages_names }}'

# - name: Install python packages
#   pip:
#     name: '{{ item }}'
#   with_items: '{{ dhcpd__pip_packages_names|list }}'
#   when: dhcpd__pip_packages_names|length > 0
