---
# tasks file for dhcpd

- name: Include the OS specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - defaults.yml
      skip: true
  tags: ['always']

- name: Check role availability
  fail:
    msg: This module only works with systemd
  when: ansible_service_mgr != 'systemd'

- name: Import init tasks
  import_tasks: init.yml
  tags: ['always']

- name: Import install tasks
  import_tasks: install.yml
  tags: ['dhcpd', 'dhcpd-install']

- name: Import configuration tasks
  import_tasks: configure.yml
  tags: ['dhcpd', 'dhcpd-configure']

- name: Import service tasks
  import_tasks: service.yml
  tags: ['dhcpd', 'dhcpd-service']

- name: Configure dhcpd instances
  include_tasks: types/instance_{{ outer_item.value.mode }}.yml
  vars:
    dhcpd__instance: "{{ dhcpd__instance_defaults|combine(outer_item.value)|combine({'name': outer_item.key}) }}"
  with_dict: '{{ dhcpd__instances }}'
  loop_control:
    loop_var: outer_item
  tags: ['dhcpd', 'dhcpd-configure']

- name: Optionally include facts tasks
  include_tasks: facts.yml
  when: dhcpd__facts|bool
  tags: ['dhcpd', 'dhcpd-facts']
