---
# tasks file for dhcpd

- name: Include the OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
        - "{{ ansible_distribution }}.yml"
        - "{{ ansible_os_family }}.yml"
        - "defaults.yml"
      skip: true
  tags: ['always']

- import_tasks: init.yml
  tags: ['always']

- import_tasks: install.yml
  tags: ['dhcpd', 'dhcpd-install']

- import_tasks: configure.yml
  tags: ['dhcpd', 'dhcpd-configure']

- import_tasks: service.yml
  tags: ['dhcpd', 'dhcpd-service']

- include_tasks: facts.yml
  when: dhcpd__facts|bool
