---
- name: Assert required LDAP variables
  assert:
    that:
      - True
  tags: ['dhcpd']

- name: Configure DHCP server
  template:
    src: 'dhcpd.conf.files.j2'
    dest: '{{ dhcpd__config_file }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ 'restart-dhcpd' ]
  tags: ['dhcpd']
