---

- name: Include common instance ending tasks
  include_tasks: types/_header.yml
  tags: ['dhcpd', 'dhcpd-configure']

# TODO
- name: Assert required FILES variables
  assert:
    that:
      - true

- name: Include common instance ending tasks
  include_tasks: types/_footer.yml
  tags: ['dhcpd', 'dhcpd-configure']
